name: Code Coverage Validation

on:
  pull_request:
    branches:
      - master

env:
    CAMINHO_PROJETO_TESTES: ./PointOfInterestByGpsUnitTests

jobs:
      tests:
    
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v2
    
        - name: Setup .NET 5
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 5.0.102
    
        - name: Testes com .NET 5 + xUnit + Fluent Assertions + Coverlet
          run: dotnet test ${{ env.CAMINHO_PROJETO_TESTES }} --verbosity minimal --logger:"html;LogFileName=resultado-testes.html" --collect:"XPlat Code Coverage"
    
        - name: Instalar ReportGenerator
          if: success()
          run: dotnet tool install --global dotnet-reportgenerator-globaltool --version 4.8.4
      
        - name: Gerar relatório de cobertura de testes com ReportGenerator
          if: success()
          run: |
            cd ${{ env.CAMINHO_PROJETO_TESTES }}/TestResults
            # Acessar diretório gerado com o XML de Cobertura de código
            cd $(ls -d */|head -n 1)
            reportgenerator "-reports:coverage.cobertura.xml" "-targetdir:coveragereport" -reporttypes:Html
    